line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - PartyHub/Sources/Generated
  - PartyHub/Managers
